### ISSUE TITLE
Classement.html

### ISSUE THREAD

**Issue by Knackie** [Knackie/ChessTracker#3]
I've make a little leaderboard in index.html, but want to make a generic leaderboard in classement.html. 
If someone can help me.

**Comment by Divjyo15** [comment]
hey @knackie can you plz elaborate more

**Comment by Knackie** [comment]
Yes, i want to make a hole website, with classement for each people, with

**Comment by Knackie** [comment]
> hey @Knackie can you plz elaborate more

Yes, it's done actually
