### ISSUE TITLE
Makes pages for players

### ISSUE THREAD

**Issue by Knackie** [Knackie/ChessTracker#7]
Hi, actually i've an historic & leaderboard for games.
I need now a page that be update for each player with data players ( percent winrate versus who, total winrate, winrate pro opening..., pro day)

**Comment by pBouillon** [comment]
FYI, I started something on #9, the template can now be populated with what you want to display

**Comment by Knackie** [comment]
#9cba88b4e541ece61aea9117e953408e7b0c20ee added for leaderboard
